### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by tommasoc80** [researchpy/documentation#1]
Hi, 
I've installed researchpy on my Mac and on an Ubuntu machine, but when import the module I got this error:

 File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/researchpy/__init__.py", line 10, in <module>
    from .ttest import ttest
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/researchpy/ttest.py", line 157
    correction= f"{correction}")

SyntaxError: invalid syntax

Thanks!

**Comment by researchpy** [comment]
Hey here, sorry for the delay in getting to this. It's the line "from .ttest import ttest" which is incorrect. It should be "from researchpy import ttest".

Best,

Corey

**Comment by geofrunz** [comment]
Dear Corey,
sorry for disturbing you...I've tried to replace 
"from researchpy import ttest" with **from researchpy import ttest* in the __init__.py file
but I still get the same error reported by tommasoc80,
do you have any alternative solution?
Thank you in advance
Giovanni

**Comment by Guindillator** [comment]
I'm getting the same error also..

**Comment by Corey-Bryant** [comment]
Hey Giovanni and Guindillator,

I apologize for taking so long to see this notification.  Do you both also have it installed on a Mac and on an Ubuntu machine? Also, which version are you using? The most up-to-date released version at this time is 0.1.6.

The init.py file should contain

```
from .ttest import ttest
from .summary import *
from .correlation import *
from .crosstab import *
```

**Comment by pankajigec26** [comment]
I am facing this issue in both version 0.1.6 and 0.1.7

and .init. file is containing 

```
> # -*- coding: utf-8 -*-
> """
> 
> @author: Corey Bryant
> 
> Last udpated: 08/28/2018
> 
> """
> 
> from .ttest import ttest
> from .summary import *
> from .correlation import *
> from .crosstab import *
> 
> 
> 
> 
> 
```

**Comment by researchpy** [comment]
Thanks for notifying me, what type of computer do you have it installed on?

**Comment by researchpy** [comment]
Could you try replacing:

from .ttest import ttest

With:

from .ttest import *


Thanks,

Corey

**Comment by gotzillaz** [comment]
> Hi,
> I've installed researchpy on my Mac and on an Ubuntu machine, but when import the module I got this error:
> 
> File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/researchpy/**init**.py", line 10, in 
> from .ttest import ttest
> File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/researchpy/ttest.py", line 157
> correction= f"{correction}")
> 
> SyntaxError: invalid syntax
> 
> Thanks!

I just got the same issue.
However, I found that the library requires **python3.6** in order to execute f-string literal.
After switching from **python3.5 to python3.6**, everything works fine for me.

**Comment by researchpy** [comment]
Thank you gotzillaz!

Best,

Corey
