### ISSUE TITLE
summary_cont and summary_cat Errors

### ISSUE THREAD

**Issue by hrnaltun** [researchpy/documentation#6]
rp.summary_cont(df[["total_bill","tip","size"]])

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_14992\394631906.py in ?()
----> 1 rp.summary_cont(df[["total_bill","tip","size"]])

~\anaconda3\Lib\site-packages\researchpy\summary.py in ?(group1, conf, decimals)
     56                                     f'{conf_level} Conf.', 'Interval'])
     57 
     58         count = 0
     59 
---> 60         for ix, df_col in group1.iteritems():
     61 
     62             count = count + 1
     63 

~\anaconda3\Lib\site-packages\pandas\core\generic.py in ?(self, name)
   6200             and name not in self._accessors
   6201             and self._info_axis._can_hold_identifiers_and_holds_name(name)
   6202         ):
   6203             return self[name]
-> 6204         return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'iteritems'

Is there a solution for this problem? 

rp.summary_cat(df[["sex", "smoker", "day"]])

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_14992\1569291090.py in ?()
----> 1 rp.summary_cat(df[["sex", "smoker", "day"]])

~\anaconda3\Lib\site-packages\researchpy\summary.py in ?(group1, ascending)
    221     elif type(group1) == pandas.core.frame.DataFrame:
    222 
    223         count = 0
    224 
--> 225         for ix, df_col in group1.iteritems():
    226 
    227             count = count + 1
    228 

~\anaconda3\Lib\site-packages\pandas\core\generic.py in ?(self, name)
   6200             and name not in self._accessors
   6201             and self._info_axis._can_hold_identifiers_and_holds_name(name)
   6202         ):
   6203             return self[name]
-> 6204         return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'iteritems'

Also for this one?

**Comment by Corey-Bryant** [comment]
Thank you for the flag! This has been addressed and the new version will be released in March.
